# Generated by Django 6.0.4 on 2026-05-04 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Ngày tạo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="update_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Ngày tạo",
            ),
            preserve_default=False,
        ),
    ]
