# Generated by Django 6.0.4 on 2026-05-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_created_at_user_update_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="update_at",
        ),
    ]
