# Generated by Django 6.0.4 on 2026-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Vị trí"
            ),
        ),
    ]
