# Generated by Django 6.0.4 on 2026-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_citizenprofile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizenprofile",
            name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Vị trí"
            ),
        ),
    ]
