# Generated by Django 6.0.4 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_citizenprofile_address_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescuerprofile",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Số CCCD/CMND"
            ),
        ),
    ]
