# Generated by Django 6.0.4 on 2026-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rescuerprofile_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescuerprofile",
            name="activation_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mã kích hoạt"
            ),
        ),
    ]
