# Generated by Django 6.0.4 on 2026-05-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rescuerprofile_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescuerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("ACTIVE", "Đang hoạt động"),
                    ("BANNED", "Đã bị khóa"),
                ],
                default="PENDING",
                verbose_name="Trạng thái",
            ),
        ),
    ]
