# Generated by Django 6.0.4 on 2026-05-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rescuerprofile_activation_code"),
        ("rescue_operations", "0002_remove_sosimage_image_url_sosimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="expo_push_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Expo Push Token"
            ),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citizens",
                to="rescue_operations.zone",
                verbose_name="Khu vực sinh sống",
            ),
        ),
    ]
