# Generated by Django 6.0.4 on 2026-05-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rescuerprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rescuerprofile",
            name="activation_code",
        ),
    ]
