# Generated by Django 5.2.14 on 2026-09-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_rescuerprofile_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuerprofile',
            name='team_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='account_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rescuerprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('ACTIVE', 'Đang hoạt động'), ('BANNED', 'Đã bị khóa'), ('REJECTED', 'Bị từ chối')], default='PENDING', verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
