# Generated by Django 5.2.14 on 2026-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rescuerprofile_team_code_user_account_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedSession',
            fields=[
                ('sid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
