# Generated by Django 6.0.4 on 2026-05-03 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rescue_operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tiêu đề cảnh báo"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nội dung chi tiết"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Loại cảnh báo",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Mức độ nghiêm trọng",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "Hệ thống"),
                            ("COMMUNITY", "Cộng đồng"),
                            ("AUTHORITY", "Cơ quan chức năng"),
                            ("AI", "AI"),
                        ],
                        default="SYSTEM",
                        max_length=15,
                        verbose_name="Nguồn phát tin",
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Vĩ độ",
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Kinh độ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Còn hiệu lực"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="rescue_operations.zone",
                        verbose_name="Vùng sự cố liên quan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cảnh báo",
                "verbose_name_plural": "Cảnh báo",
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("TRUE", "Đúng / Còn nguy hiểm"),
                            ("FALSE", "Sai / Tin giả"),
                            ("STILL_DANGER", "Vẫn còn nguy hiểm"),
                            ("RESCUED", "Đã được cứu hộ"),
                        ],
                        max_length=15,
                        verbose_name="Kết quả xác nhận",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian vote"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="communications.alert",
                        verbose_name="Cảnh báo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người vote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xác nhận cảnh báo",
                "verbose_name_plural": "Xác nhận cảnh báo",
                "db_table": "alert_votes",
                "unique_together": {("alert", "user")},
            },
        ),
    ]
