# Generated by Django 5.2.14 on 2026-09-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_backfill_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
