# Generated by Django 6.0.4 on 2026-05-03 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên khu vực")),
                (
                    "sector_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mã khu vực"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Đang xảy ra"),
                            ("STABILIZING", "Đang ổn định"),
                            ("RESOLVED", "Đã giải quyết"),
                            ("STANDBY", "Chờ"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Nguy cấp"),
                            ("HIGH", "Cao"),
                            ("MEDIUM", "Trung bình"),
                            ("LOW", "Thấp"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Mức độ nghiêm trọng",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Loại sự cố"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả chi tiết"
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Vĩ độ trung tâm"
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        decimal_places=7,
                        max_digits=10,
                        verbose_name="Kinh độ trung tâm",
                    ),
                ),
                (
                    "people_affected",
                    models.IntegerField(default=0, verbose_name="Số nạn nhân ước tính"),
                ),
                (
                    "rescuers_needed",
                    models.IntegerField(default=0, verbose_name="Số cứu hộ viên cần"),
                ),
                (
                    "ai_priority_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Điểm ưu tiên AI",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vùng sự cố",
                "verbose_name_plural": "Vùng sự cố",
                "db_table": "zones",
            },
        ),
        migrations.CreateModel(
            name="SOSSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("SOS", "SOS khẩn cấp"), ("PING", "Ping vị trí")],
                        default="SOS",
                        max_length=5,
                        verbose_name="Loại tín hiệu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("ACKNOWLEDGED", "Đã tiếp nhận"),
                            ("IN_PROGRESS", "Đang xử lý"),
                            ("RESOLVED", "Đã giải quyết"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Vĩ độ"
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Kinh độ"
                    ),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Loại khẩn cấp",
                    ),
                ),
                (
                    "people_count",
                    models.IntegerField(default=1, verbose_name="Số người cần cứu"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời điểm gửi"
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sos_signals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sos_signals",
                        to="rescue_operations.zone",
                        verbose_name="Vùng sự cố",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tín hiệu SOS",
                "verbose_name_plural": "Tín hiệu SOS",
                "db_table": "sos_signals",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SOSImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.TextField(verbose_name="Link ảnh hiện trường")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chú thích"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tải lên"
                    ),
                ),
                (
                    "sos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rescue_operations.sossignal",
                        verbose_name="Tín hiệu SOS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh SOS",
                "verbose_name_plural": "Ảnh SOS",
                "db_table": "sos_images",
            },
        ),
    ]
