# Generated by Django 5.2.8 on 2026-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rescue_operations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sosimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="sosimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sos_images/%Y/%m/%d/",
                verbose_name="Ảnh hiện trường",
            ),
        ),
    ]
