# Generated by Django 5.2.14 on 2026-09-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_mission_allocated_staff_mission_allocated_vehicles_and_more'),
        ('rescue_operations', '0002_remove_sosimage_image_url_sosimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sossignal',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='assigned_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos', to='reporting.mission'),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='location_source',
            field=models.CharField(default='GPS', max_length=20),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='request_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Chưa xác minh'), ('CHECKING', 'Đang xác minh'), ('VERIFIED', 'Đã xác minh'), ('INCORRECT', 'Thông tin không chính xác')], default='UNVERIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rescue_operations.sossignal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
