# Generated by Django 5.2.14 on 2026-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_operations', '0003_sossignal_address_sossignal_assigned_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sossignal',
            name='supplies_delivered',
            field=models.JSONField(blank=True, default=dict, verbose_name='Đã tiếp tế'),
        ),
        migrations.AddField(
            model_name='sossignal',
            name='supplies_needed',
            field=models.JSONField(blank=True, default=dict, verbose_name='Nhu cầu cứu trợ'),
        ),
    ]
