# Generated by Django 5.2.14 on 2026-09-07 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_mission_idx_mission_resc_status_and_more'),
        ('rescue_operations', '0004_sossignal_supplies_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sossignal',
            index=models.Index(fields=['zone', 'status'], name='idx_sos_zone_status'),
        ),
        migrations.AddIndex(
            model_name='sossignal',
            index=models.Index(fields=['status', '-sent_at'], name='idx_sos_status_sent'),
        ),
        migrations.AddIndex(
            model_name='sossignal',
            index=models.Index(fields=['verification_status', 'status'], name='idx_sos_verify_status'),
        ),
    ]
