# Generated by Django 5.2.14 on 2026-05-26 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_platform', models.CharField(choices=[('VNEXPRESS', 'VnExpress'), ('TUOITRE', 'Tuổi Trẻ'), ('THANHNIEN', 'Thanh Niên'), ('GDACS', 'GDACS (Quốc tế)'), ('OTHER', 'Nguồn khác')], default='OTHER', max_length=20, verbose_name='Nền tảng nguồn')),
                ('source_url', models.TextField(unique=True, verbose_name='URL gốc')),
                ('raw_title', models.TextField(blank=True, null=True, verbose_name='Tiêu đề gốc')),
                ('raw_content', models.TextField(verbose_name='Nội dung thô')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='MD5 hash nội dung')),
                ('extracted_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa danh trích xuất')),
                ('extracted_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('extracted_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kinh độ')),
                ('extracted_severity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mức độ nghiêm trọng')),
                ('extracted_incident_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại sự cố')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Độ tin cậy (0-1)')),
                ('status', models.CharField(choices=[('RAW', 'Thô - Chưa phân tích'), ('ANALYZED', 'Đã phân tích NLP'), ('APPROVED', 'Đã duyệt - Chờ tạo Alert'), ('ALERT_CREATED', 'Đã tạo Alert'), ('REJECTED', 'Bị từ chối (Tin giả / Trùng)')], default='RAW', max_length=15, verbose_name='Trạng thái')),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lý do từ chối')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian crawl')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phân tích')),
                ('linked_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_sources', to='communications.alert', verbose_name='Alert đã tạo')),
            ],
            options={
                'verbose_name': 'Bài viết đã crawl',
                'verbose_name_plural': 'Bài viết đã crawl',
                'db_table': 'crawled_articles',
                'ordering': ['-crawled_at'],
            },
        ),
    ]
