# Generated by Django 5.2.14 on 2026-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledarticle',
            name='extracted_address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ chi tiết (trích xuất)'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='extracted_people_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số người cần cứu (trích xuất)'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='extracted_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT liên hệ (trích xuất)'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='facebook_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Người đăng (Facebook)'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='facebook_post_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Facebook Post ID'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='fb_reactions_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượt react Facebook'),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='has_media',
            field=models.BooleanField(default=False, verbose_name='Có đính kèm ảnh/video'),
        ),
        migrations.AlterField(
            model_name='crawledarticle',
            name='source_platform',
            field=models.CharField(choices=[('VNEXPRESS', 'VnExpress'), ('TUOITRE', 'Tuổi Trẻ'), ('THANHNIEN', 'Thanh Niên'), ('GDACS', 'GDACS (Quốc tế)'), ('FACEBOOK', 'Facebook Groups'), ('OTHER', 'Nguồn khác')], default='OTHER', max_length=20, verbose_name='Nền tảng nguồn'),
        ),
    ]
