# Generated by Django 5.2.14 on 2026-05-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_facebook_sos_fields'),
        ('rescue_operations', '0002_remove_sosimage_image_url_sosimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledarticle',
            name='linked_sos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_sources', to='rescue_operations.sossignal', verbose_name='SOS đã tạo'),
        ),
    ]
