# Generated by Django 5.2.14 on 2026-09-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_add_linked_sos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledarticle',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledarticle',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawledarticle',
            name='status',
            field=models.CharField(choices=[('RAW', 'Thô - Chưa phân tích'), ('ANALYZED', 'Đã phân tích NLP'), ('APPROVED', 'Đã duyệt'), ('ALERT_CREATED', 'Đã tạo Alert'), ('REJECTED', 'Bị từ chối (Tin giả / Trùng)')], default='RAW', max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='NewsPublicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PUBLISHED', 'Xuất bản'), ('UNPUBLISHED', 'Gỡ xuất bản'), ('ALERT_CREATED', 'Tạo cảnh báo')], max_length=20)),
                ('alert_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_events', to='ai.crawledarticle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
