# Generated by Django 6.0.4 on 2026-05-03 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rescue_operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vai trò trong nhiệm vụ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Đang thực hiện"),
                            ("COMPLETED", "Hoàn thành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời điểm tham gia"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm hoàn thành"
                    ),
                ),
                (
                    "rescuer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cứu hộ viên",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="rescue_operations.zone",
                        verbose_name="Vùng nhiệm vụ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhiệm vụ",
                "verbose_name_plural": "Nhiệm vụ",
                "db_table": "missions",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Loại phương tiện",
                    ),
                ),
                (
                    "specialty_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Chuyên môn nguồn lực",
                    ),
                ),
                (
                    "supplies",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Chi tiết vật tư (JSON)"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Sẵn sàng điều phối"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rescuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chủ sở hữu nguồn lực",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nguồn lực",
                "verbose_name_plural": "Nguồn lực",
                "db_table": "resources",
            },
        ),
    ]
