# Generated by Django 6.0.4 on 2026-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="specialty_type",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="supplies",
        ),
        migrations.AddField(
            model_name="resource",
            name="number_staff",
            field=models.IntegerField(
                default=1, verbose_name="Số lượng thành viên trong nhóm"
            ),
        ),
    ]
