# Generated by Django 6.0.4 on 2026-05-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_remove_resource_specialty_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Đang thực hiện"),
                    ("COMPLETED", "Hoàn thành"),
                    ("CANCELLED", "Đã hủy"),
                    ("ON_MY_WAY", "Chưa tiếp cận"),
                    ("NEEDS_HELP", "cần hỗ trợ"),
                ],
                default="ACTIVE",
                max_length=15,
                verbose_name="Trạng thái",
            ),
        ),
    ]
