# Generated by Django 5.2.14 on 2026-09-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_mission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='allocated_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='allocated_vehicles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='outcome_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='supplies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='vehicle_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resource',
            name='verification_status',
            field=models.CharField(default='SELF_DECLARED', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING_ACCEPTANCE', 'Chờ đội nhận'), ('ACCEPTED', 'Đã nhận'), ('ACTIVE', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('ON_MY_WAY', 'Chưa tiếp cận'), ('NEEDS_HELP', 'cần hỗ trợ')], default='PENDING_ACCEPTANCE', max_length=24, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reporting.mission')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='reporting.mission')),
                ('supporting_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_requests', to='reporting.mission')),
            ],
        ),
    ]
