# Generated by Django 5.2.14 on 2026-09-07 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_mission_allocated_staff_mission_allocated_vehicles_and_more'),
        ('rescue_operations', '0004_sossignal_supplies_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['rescuer', 'status'], name='idx_mission_resc_status'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['zone', 'status'], name='idx_mission_zone_status'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status', 'mission'], name='idx_support_status'),
        ),
    ]
